### ISSUE TITLE
trilead ssh suspected too old

### ISSUE THREAD

**Issue by ipelupessy** [JungleComputing/smartsockets#1]
this references an issue discussed with @jmaassen  where connections over ssh between two hubs fail. Since the hubs where started using xenon with a newer ssh library (sshd) we suspect that the trilead ssh fails to negotiate a protocol. (circumstantial evidence for this is the fact that the machine in question was updated around time of failure...)

```
13:47:02.374 [HubConnector] INFO  ibis.smartsockets.direct - Direct connection failed: 5033 ms.
13:47:02.374 [HubConnector] DEBUG ibis.smartsockets.direct - Attempting SSH connection to 132..x.x.x -42737~pxxxxxxx+22 via host 132.x.x.x local port = 0 timeout = 4967
Enabling debugging: true
Enabling debugging
13:47:02.414 [HubConnector] DEBUG ibis.smartsockets.direct - com.trilead.ssh2.transport.TransportConnection: Sent SSH_MSG_KEXINIT 478 bytes payload
13:47:02.416 [Thread-52] DEBUG ibis.smartsockets.direct - com.trilead.ssh2.transport.TransportConnection: Received SSH_MSG_KEXINIT 867 bytes payload
13:47:02.418 [Thread-52] DEBUG ibis.smartsockets.direct - com.trilead.ssh2.transport.TransportManager: Receive thread: error in receiveLoop: Cannot negotiate, proposals do not match.
13:47:02.418 [Thread-52] DEBUG ibis.smartsockets.direct - com.trilead.ssh2.transport.TransportManager: Receive thread: back from receiveLoop
13:47:02.419 [HubConnector] INFO  ibis.smartsockets.direct - SSH connection failed: 45 ms.
13:47:02.419 [HubConnector] DEBUG i.smartsockets.hub.connections.hub - Got exception!
ibis.smartsockets.direct.NestedIOException: Connection setup failed (single attempt)!
	at ibis.smartsockets.direct.DirectSocketFactory.createSocket(DirectSocketFactory.java:1658) ~[smartsockets-1.71.jar:na]
	at ibis.smartsockets.hub.Connector.createConnection(Connector.java:163) [smartsockets-1.71.jar:na]
	at ibis.smartsockets.hub.Connector.handleNewHub(Connector.java:302) [smartsockets-1.71.jar:na]
	at ibis.smartsockets.hub.Connector.run(Connector.java:311) [smartsockets-1.71.jar:na]
	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_201]
13:47:02.419 [HubConnector] INFO  i.smartsockets.hub.connections.hub - Failed to set up connection!
```

**Comment by jmaassen** [comment]
I've started working on this in the SSH-replacement branch

**Comment by ipelupessy** [comment]
ok, let me know when its ready to test...

**Comment by ipelupessy** [comment]
it seems to work now! 
it stumbled on a ip6 address in known_hosts, removing this it works,
need a little bit more testing
